id: P010690
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:03.895891
source_metadata:
  id: bdr:W1PD88990
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༡༦༽
  author: ''
  volumes:
    32e531900d4a41acbd006d2fa7425b1a:
      image_group_id: I1PD89009
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
