id: P010690
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD88990
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༡༦༽
  author: ''
  volumes:
    32e531900d4a41acbd006d2fa7425b1a:
      image_group_id: I1PD89009
      title: ''
      volume_number: 1
      total_pages: 132
